APIVersion: 0
data:
  networkrulesetpolicies:

    - name: ingress-backend-rs
      propagate: true
      incomingRules:
        - action: Allow
          logsDisabled: false
          object:
            - - 'externalnetwork:name=public'
          observationEnabled: false
          protocolPorts:
            - any
      subject:
        - - '@org:cloudaccount=jtb75-002'
          - '@org:group=demo-eks-dWeJ'
          - '@org:kubernetes=ingress'
          - '@org:tenant=806079892264890368'
          - app=default-backend

    - name: ingress-intra-rs
      incomingRules:
        - action: Allow
          logsDisabled: false
          object:
            - - '@org:cloudaccount=jtb75-002'
              - '@org:group=demo-eks-dWeJ'
              - '@org:kubernetes=ingress'
              - '@org:tenant=806079892264890368'
          observationEnabled: false
          protocolPorts:
            - any
      outgoingRules:
        - action: Allow
          logsDisabled: false
          object:
            - - '@org:cloudaccount=jtb75-002'
              - '@org:group=demo-eks-dWeJ'
              - '@org:kubernetes=ingress'
              - '@org:tenant=806079892264890368'
          observationEnabled: false
          protocolPorts:
            - any
      propagate: true
      subject:
        - - '@org:cloudaccount=jtb75-002'
          - '@org:group=demo-eks-dWeJ'
          - '@org:kubernetes=ingress'
          - '@org:tenant=806079892264890368'

    - name: ingress-lb-rs
      incomingRules:
        - action: Allow
          logsDisabled: false
          object:
            - - 'externalnetwork:name=public'
          observationEnabled: false
          protocolPorts:
            - any
      outgoingRules:
        - action: Allow
          logsDisabled: false
          object:
            - - 'externalnetwork:name=public'
          observationEnabled: false
          protocolPorts:
            - any
        - action: Allow
          logsDisabled: false
          object:
            - - '@org:cloudaccount=jtb75-002'
              - '@org:group=demo-eks-dWeJ'
              - '@org:kubernetes=voting'
              - '@org:tenant=806079892264890368'
              - app=azure-vote-front
          observationEnabled: false
          protocolPorts:
            - any
      propagate: true
      subject:
        - - '@org:cloudaccount=jtb75-002'
          - '@org:group=demo-eks-dWeJ'
          - '@org:kubernetes=ingress'
          - '@org:tenant=806079892264890368'

identities:
  - networkrulesetpolicy
label: Snapperripple Snout